//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具生成。
//     執行時版本:4.0.30319.42000
//
//     對此檔案的更改可能會導致不正確的行為，並且如果
//     重新生成程式碼，這些更改將會丟失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoeLoaderDelta.Properties {
    using System;
    
    
    /// <summary>
    ///   一個強類型的資源類，用於尋找本地化的字串等。
    /// </summary>
    // 此類是由 StronglyTypedResourceBuilder
    // 類透過類似於 ResGen 或 Visual Studio 的工具自動生成的。
    // 若要添加或移除成員，請編輯 .ResX 檔案，然後重新執行 ResGen
    // (以 /str 作為命令選項)，或重新生成 VS 項目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此類使用的快取的 ResourceManager 實例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoeLoaderDelta.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此強類型資源類，為所有資源尋找
        ///   重寫當前執行緒的 CurrentUICulture 屬性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   尋找類似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///&lt;startup useLegacyV2RuntimeActivationPolicy=&quot;true&quot;&gt;&lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.5.1&quot;/&gt;&lt;/startup&gt;
        ///  &lt;runtime&gt;
        ///    &lt;gcConcurrent enabled=&quot;true&quot; /&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;publisherPolicy apply=&quot;yes&quot; /&gt;
        ///      &lt;probing privatePath=&quot;lib&quot; /&gt;
        ///    &lt;/assemblyBinding&gt;
        ///  &lt;/runtime&gt;
        ///&lt;/configuration&gt; 的本地化字串。
        /// </summary>
        internal static string exeConfig {
            get {
                return ResourceManager.GetString("exeConfig", resourceCulture);
            }
        }
    }
}
